# Generated by Django 2.2.24 on 2021-12-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=60)),
                ('ic', models.CharField(max_length=60)),
                ('dist', models.CharField(max_length=60)),
            ],
        ),
    ]
